### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by honjen** [mollila666/tsoha-keskustelusovellus-mo-2024#1]
Hyvää:
Sovelluksen kehitys on pitkällä ja README tiedostossa listatut toiminnallisuudet löytyvät ja toimivat pääpiirteittäin muutamia huomautuksia lukuunottamatta. Koodi on jaoteltu hyvin eri osiin.

Huomioita:
- requirements.txt sisältää todella paljon riippuvuuksia, joilla ei nähtävästi ole mitään todellista tarvetta sovelluksen käytölle. Tiedoston suorittaminen aiheuttaa useita virheitä, sillä useita listattuja riippuvuuksia ei edes löydy asennettavaksi. Sovelluksen testaamista varten jouduin käyttämään oman sovellukseni requirements.txt tiedostoa, joka on kuvattuna alla.
![requirements](https://github.com/user-attachments/assets/000f9bdc-27d0-4b8e-82b5-d7bfe7e38416)
- Koodissa tehdään useasti pythonin puolella asioita, joita voisi hoitaa SQL-haussa, mikä tekee koodista hieman monimutkaisempaa.
- Muiden viestejä voi muokata kirjautumatta sisään kirjoittamalla osoitekenttään viestin muokkauksen osoitteen.
- Keskusteluketjuissa viestin lähettäjän nimeä tai lähetysajankohtaa ei näy, jolloin ketjun viestit vaikuttavat hieman sekavilta.
- Uusia ketjuja tai viestejä voi yrittää tehdä vaikka ei olisi kirjautunut sisään, mikä aiheuttaa sovelluksessa virheen.
- Salaiselle alueelle pääsee osoitekentän kautta, vaikka ei olisi kirjautunut sisään. Salaiselle ketjulle voi myös tällöin kirjautuneena kirjoittaa viestejä, vaikka ei olisi lupaa olla ketjulla.

**Comment by mollila666** [comment]
Hei, 

Kiitokset yksityiskohtaisesta palautteesta, erinomaisia vinkkejä korjauksiin!

**Comment by mollila666** [comment]
Hei,

Kiitokset yksityiskohtaisesta palautteesta, erinomaisia vinkkejä korjauksiin!
