### ISSUE TITLE
Veraisarviointi 2

### ISSUE THREAD

**Issue by JuhoTurunen** [mollila666/tsoha-keskustelusovellus-mo-2024#2]
Sovellus on kaikkiaan hyvällä tasolla, joten olen osittain aika pikkutarkka palautteessa, etenkin käyttökokemuksen osiossa. 

## Käyttökokemus
- Sain sovelluksen toimimaan hyvin, mutta kun kirjauduin sisään väärällä tunnuksella, minut ohjattiin toiseen ikkunaan, jossa ilmoitettiin tunnuksen tai salasanan olevan väärä. Kun painoin sivulla olevaa "palaa takaisin nappia" se ohjasi minut rekisteröinti sivulle, eikä kirjautumissivulle. Käyttäjäystävällisyyden kannalta tämän ilmoituksen voisi tuoda itse kirjautumissivulle, vaikkapa Flash viestin avulla.
- Ylläpitäjänä, kun sovelluksen keskusteluaiheiden ja käyttäjien määrä kasvaa, on vaikea hallita alueiden poistoa taikka käyttäjien lisäämistä salaiselle alueelle, sillä ylläpitäjältä puuttuu hakutoiminto.
- Ylläpitäjän työkaluihin pääsee sekä yläpalkista että alhaalla olevasta linkistä. Samoin "Kirjaudu ulos" nappi sekä omat viestiketjut löytyvät sekä yläpalkista että alhaalta. Nämä voisivat olla esimerkiksi pelkästään yläpalkissa, joka siistisi ulkoasua. 
- Salaiset alueet eivät näyttäneet toimivan. Toinen ”käyttäjä” tason käyttäjä kykeni näkemään ja kirjoittamaan salaiselle alueelle, vaikkei häntä ollut lisätty sille.
- Aikastampit annetaan ketjuissa puhtaina ja epäformatoituna, pitkillä desimaali sekunneilla. Tätä ajan ilmaisua voisi siistiä pyöristämällä sekunteihin tai minuutteihin.
- Viestien haku on Case sensitiivinen, joka voi vaikeuttaa haluttujen viestejen löytöä.
- Omat viestiketjut osio näyttää sekä omat että myös muiden tekemät viestiketjut, joista omat ovat sinisellä ilmaistu. Kuitenkin kun viestejä ja viestiketjuja tulee sivulle lisää, omat viestit hukkuvat koko viestipalstan viestien sekaan. Etenkin koska vanhin viesti näytetään ylimpänä ja koska omissa viesteissä ei ole hakutoimintoa. Tällä sivulla voisi näyttää vain ne viestiketjut ja viestit, jotka on itse tehnyt.

## Koodi
- Suosittelen f stringejen käyttöä, jos tekstin sisällä joutuu käyttämään muuttujia.
- Koodissa on minun ymmärrykseni mukaan SQL injektio heikkous. Sen sijaan että asetat muuttujat suoraan SQL viestiin, voit luoda parametrisoidun querryn esimerkiksi näin: 
sql = text("INSERT INTO users (name, password, role) VALUES (:name, :password, :role)")
db.session.execute(sql, {"name": name, "password": hash_value, "role": role})
- Suosittelen käyttämään kuvaavampia muuttujien nimiä yksittäisten kirjainten sijaan. Tämä helpottaa koodin lukemista.
- Suosittelen linnterin (kuten pylint) käyttöä koodin siistimiseen.
- Flash abort kutsutaan monta kertaa, mutta sitä ei ole importoitu flaskista.

Kaikkiaan sovellus on hyvin tehty, vaikka osa toiminnoista näyttäisi olevankin rikki. Hienoa työtä!

**Comment by mollila666** [comment]
Kiitos erinomaisista kommenteista.
